import type { OnePagerListItem } from "@/types/onePager";

/** Landing-page subset shaped like sampleData (full form stays in sampleData.ts). */
export const landingOnePagers: OnePagerListItem[] = [
  {
    market: "National",
    retailer: "Supermarket",
    category: "Hair Care",
    campaign_focus: "Summer Freshness",
    channel: "Supermarket",
    title: "National-Supermarket-Haircare-Summer Freshness-US",
    business_outcome_statement:
      "Drive 12% category sales uplift and secure primary share-of-shelf leadership across premium hair ranges via cross-channel superior branding.",
    scoring_mode: "UNWEIGHTED",
    status: "ACTIVE",
    created_by: "user-001",
    published_at: "15 Jun 2026, 20:00",
    pillars: [],
  },
  {
    market: "National",
    retailer: "Supermarket",
    category: "Hair Care",
    campaign_focus: "Summer Freshness",
    channel: "Supermarket",
    title: "National-Supermarket-Haircare-Summer Freshness-US",
    business_outcome_statement:
      "Drive 12% category sales uplift and secure primary share-of-shelf leadership across premium hair ranges via cross-channel superior branding.",
    scoring_mode: "WEIGHTED",
    status: "ACTIVE",
    created_by: "user-002",
    published_at: "15 Jun 2026, 20:00",
    pillars: [],
  },
  {
    market: "National",
    retailer: "All Retailers",
    category: "Execution Excellence",
    campaign_focus: "National Growth Program",
    channel: "All Channels",
    title: "National Execution Excellence One-Pager 2026",
    business_outcome_statement:
      "Improve execution quality, customer engagement, availability, and sales performance across all regions.",
    scoring_mode: "WEIGHTED",
    status: "DRAFT",
    created_by: "user-001",
    published_at: "10 Jun 2026, 09:30",
    pillars: [],
  },
  {
    market: "US",
    retailer: "Walmart",
    category: "Oral Care",
    campaign_focus: "Fresh Breath",
    channel: "Hypermarket",
    title: "National Oral Care Fresh breath plaque control directive",
    business_outcome_statement:
      "Improve oral care visibility and drive incremental distribution gains across priority accounts.",
    scoring_mode: "UNWEIGHTED",
    status: "DRAFT",
    created_by: "user-002",
    published_at: "01 Jun 2026, 14:00",
    pillars: [],
  },
  {
    market: "US",
    retailer: "Target",
    category: "Hair Care",
    campaign_focus: "Scalp & Shine",
    channel: "Supermarket",
    title: "National Haircare H2 Superior Scalp & Shine Focus Campaign",
    business_outcome_statement:
      "Lead with updated hero images and clear product role messaging across premium hair ranges.",
    scoring_mode: "WEIGHTED",
    status: "ARCHIVE",
    created_by: "user-001",
    published_at: "20 May 2026, 11:00",
    pillars: [],
  },
  {
    market: "National",
    retailer: "All Retailers",
    category: "Deodorants",
    campaign_focus: "Maximum Protection",
    channel: "All Channels",
    title: "Rexona Axe Maximum Protection Summer Campaign",
    business_outcome_statement:
      "Secure share of display and reinforce efficacy-led messaging for summer protection.",
    scoring_mode: "UNWEIGHTED",
    status: "ARCHIVE",
    created_by: "user-002",
    published_at: "05 May 2026, 16:45",
    pillars: [],
  },
];
